---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mcp.suse.com
  resources:
  - adapters
  - groups
  - mcpregistries
  - routeassignments
  - users
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mcp.suse.com
  resources:
  - adapters/finalizers
  - groups/finalizers
  - mcpregistries/finalizers
  - mcpservers/finalizers
  - routeassignments/finalizers
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - mcp.suse.com
  resources:
  - adapters/status
  - groups/status
  - mcpregistries/status
  - mcpservers/status
  - routeassignments/status
  - users/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mcp.suse.com
  resources:
  - agents
  - virtualmcproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mcp.suse.com
  resources:
  - mcpservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
