## Append samples of your project ##
resources:
- mcp_v1alpha1_adapter.yaml
- mcp_v1alpha1_mcpregistry.yaml
- mcp_v1alpha1_mcpserver.yaml
- mcp_v1alpha1_virtualmcproute.yaml
- mcp_v1alpha1_agent.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
